
name: lcls-inj-tuning-rhel7
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.8
  - tensorflow ==2.4
  - mkl # necessary with tensorflow and scikitlearn
  - scikit-learn ==0.23
  - numpy =1.19
  - matplotlib =3.3
  - jupyter =1.0
  - pytest =6.2
  - jedi =0.17
  - dm-tree =0.1
  - tensorflow-probability =0.12
  - pystan =2.19
  - pyepics
  - pip
  - pip:
    - gpflow ==2.1
    - scipy
    - git+https://github.com/slaclab/PyEmittance.git
